baseURL = "https://jp.60woodvale.com/"
languageCode = "en"
title = "JP Lumsdaine"
theme = "hugo-initio"


[params]
    name = "JP Lumsdaine"
    description = "Data Engineer"
    email = "jp@60woodvale.com"
    phone = "+353 87 185 4649"
    avatar = "img/Headshot.jpg"
    avatarclass = ""
    background = "img/data_background.jpg"
    banner = "img/gb_data.jpg"
    favicon = "img/favicon.ico"
    author = "JP Lumsdaine"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1



[params.google.analytics]
    trackerID = "G-NBHM2JD08C"


[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/lumsdaine"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/hawmps"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:jp@60wodvale.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
